[package]
name = "npuzzle"
version = "0.1.0"
authors = ["frmarinh", "amerelo"]

[dependencies]
piston2d-graphics = { path = "graphics/" }
piston2d-opengl_graphics = { path = "opengl_graphics/" }
piston_window = "0.73.0"
find_folder = "0.3.0"
regex = "0.2.2"
